---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weaveworks-gitops
  namespace: flux-system
spec:
  interval: 60m
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides a simple way to get insights into your GitOps workloads.
    kubernetes.io/documentation: https://docs.gitops.weave.works/docs/references/helm-reference/
  name: weaveworks-gitops
  namespace: flux-system
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  install:
    timeout: 20m
    remediation:
      retries: -1
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: weaveworks-gitops
        namespace: flux-system
  interval: 60m
  values:
    adminUser:
      create: true
      passwordHash: $2y$10$zTRdq9bLcEmGF27exGcKZ.LnSNIOpwV.n5H7tLP4/oyuSRGjTk7Ai
      username: admin
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: flux.fert.name
          paths:
            - path: /
              pathType: ImplementationSpecific
