---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  install:
    timeout: 20m
    remediation:
      retries: -1
  suspend: false
  interval: 30m
  # releaseName: kubelet-csr-approver
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 0.2.4
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: flux-system
      interval: 10m
  values:
    providerRegex: '^(master|worker)-[0-9]$'
    providerIpPrefixes: '10.0.20.0/24'
    maxExpirationSeconds: '86400'
    bypassDnsResolution: "true"
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"