---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: registry-populate
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: registry
  path: ./flux/registry/harbor-populate/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system