---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  suspend: false
  interval: 5m
  # releaseName: loki
  dependsOn:
  - name: promstack
  install:
    remediation:
      retries: -1
    timeout: 20m
  chart:
    spec:
      chart: loki
      version: 5.8.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 10m
  values:
    resources:
      requests:
        cpu: 20m
        memory: 100Mi
      limits:
        cpu: 500m
    ingress:
      enabled: true
      # ingressClassName: nginx
      hosts:
        host: loki.fert.name
    read:
      replicas: 1
    write:
      replicas: 1
    backend:
      replicas: 1
    # serviceAccount:
    #   create: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: "promstack"
      interval: ""
      # additionalLabels:
        # release: prometheus # yaml: unmarshal errors: line 11: mapping key "release" already defined at line 9
      annotations: {}
      scrapeTimeout: 30s
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1
    monitoring:
      serviceMonitor:
        # annotations: {}
        # enabled: true
        # interval: 15s
        labels:
          release: "promstack"
        # namespaceSelector: {}
        # relabelings: []
        # scheme: http
        # scrapeTimeout: null
        # tlsConfig: null
---
