kubeProxyReplacement: strict
# k8sServiceHost: 10.0.20.10
# k8sServicePort: 6443

containerRuntime:
  # integration: crio
  # socketPath: /run/crio/crio.sock
  integration: containerd
  socketPath: /run/containerd/containerd.sock
# ipam:
#   mode: "kubernetes"
  # operator:
  #   clusterPoolIPv4PodCIDR: "10.1.0.0/16"
  #   clusterPoolIPv4MaskSize: 24
hubble:
  enabled: true
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - icmp
    - http
  relay:
    enabled: true
  ui:
    enabled: true
    replicas: 1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - hubble.fert.name
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: "promstack"
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        release: "promstack"
securityContext:
  privileged: false
  seLinuxOptions:
    level: 's0'
    type: 'spc_t'
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_MODULE
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - SYS_ADMIN
    mountCgroup:
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    applySysctlOverwrites:
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    cleanCiliumState:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF