---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: defectdojo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux/security/defectdojo/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: defectdojo-populate
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux/security/defectdojo-populate/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system