---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux/security/sonarqube/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sonarqube-populate
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux/security/sonarqube-populate/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system