
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: registry
spec:
  suspend: false
  interval: 5m
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  chart:
    spec:
      chart: harbor
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: registry
      interval: 10m
  install:
    timeout: 20m
    remediation:
      retries: -1
  values:
    logLevel: debug
    expose:
      type: ingress
      ingress:
        hosts: 
          core: core.fert.name
          notary: notary.fert.name
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: local-path
          size: 5Gi
        chartmuseum:
          storageClass: local-path
          size: 1Gi
        database:
          storageClass: local-path
          size: 5Gi
        redis:
          storageClass: local-path
          size: 1Gi
        trivy:
          storageClass: local-path
          size: 1Gi
        jobservice:
          jobLog:
            storageClass: local-path
            size: 1Gi
          scanDataExports:
            storageClass: local-path
    externalURL: https://core.fert.name:443
    notary:
      enabled: false
    database:
      internal:
        resources:
          requests:
            cpu: "30m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
    trivy:
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
    # harborAdminPassword: Harbor12345
    # chartmuseum:
    #   enabled: false

    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
    # trace.enabled: 